# This file lives at $APPCONFIG/dev.nhdex/nhex.toml
# where $APPCONFIG is defined per platform:
#  * Windows: C:\Users\<username>\AppData\Roaming
#  * Linux: ~/.config
#  * Mac OS: /Users/<username>/Library/Application Support

[Network]
server = "irc.libera.chat"
port = 6697
nick = "nhex-user"
channels = "#nhex"
tls = true

[MessageBox]
show = [ "action", "privmsg", "join", "part" ]
dimJoinsAndParts = false
