# This file lives at $APPCONFIG/dev.nhdex/nhex.toml
# where $APPCONFIG is defined per platform as:
#  * Windows: C:\Users\<username>\AppData\Roaming
#  * Linux: ~/.config
#  * Mac OS: /Users/<username>/Library/Application Support

[Network]
server = "irc.libera.chat"
port = 6697
nick = "nhex-user"
# space-separated. will *not* be auto-joined until nick login *is successful*
# when `expectLoggedInAfterConnectCommands` is set to `true`.
channels = "#nhex #nhexdev"
tls = true
# per the comment above, if `expectLoggedInAfterConnectCommands` is `true`,
# one of these must be a nick(serv) identification command.
connectCommands = [
    "/msg NickServ IDENTIFY nhex-user hunter2"
]
expectLoggedInAfterConnectCommands = true

[MessageBox]
show = [ "action", "privmsg", "join", "part" ]
dimJoinsAndParts = false
showTimestamps = false
fontSize = "sm"
